SECRET_KEY: RandomeString
CONSUMER_KEY: c5cf8d94870f7520d047a0166bea53ce
CONSUMER_SECRET: f297a0ee9cec8ac2ecb100aad2b93e9927a4e45e
OAUTH_MWURI: https://meta.wikimedia.org/w
SESSION_COOKIE_SECURE: True
SESSION_REFRESH_EACH_REQUEST: False
PREFERRED_URL_SCHEME: https